//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLToPDFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLToPDFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!doctype html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///  	&lt;meta charset=&quot;utf-8&quot;&gt;&lt;/meta&gt;
        ///  	&lt;style type=&quot;text/css&quot;&gt;
        ///  		
        ///  		.data_header {
        ///  			height: 100%;
        ///  			border-collapse: collapse;
        ///  			border: 1px solid black;
        ///  			font-size: 15px;
        ///  			padding: 8px;
        ///  		}
        ///
        ///  		.doc_header_info td{
        ///  			padding: 6px;
        ///  		}
        ///
        ///  		table.border{
        ///  			border-collapse: collapse;
        ///  		}
        ///
        ///  		table.border th{
        ///  			padding: 5px;
        ///  			border: 1px solid black;
        ///  		}
        ///
        ///  		table.border td{
        ///  			padding: 5px;
        ///  	 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string invoice_template {
            get {
                return ResourceManager.GetString("invoice_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!doctype html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///  &lt;head&gt;
        ///  	&lt;meta charset=&quot;utf-8&quot;&gt;&lt;/meta&gt;
        ///  	&lt;style type=&quot;text/css&quot;&gt;
        ///  		
        ///  		.data_header {
        ///  			height: 100%;
        ///  			border-collapse: collapse;
        ///  			border: 1px solid black;
        ///  			font-size: 15px;
        ///  			padding: 8px;
        ///  		}
        ///
        ///  		.doc_header_info td{
        ///  			padding: 6px;
        ///  		}
        ///
        ///  		table.border{
        ///  			border-collapse: collapse;
        ///  		}
        ///
        ///  		table.border th{
        ///  			padding: 5px;
        ///  			border: 1px solid black;
        ///  		}
        ///
        ///  		table.border td{
        ///  			padding: 5px;
        ///  	 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string receipt_template {
            get {
                return ResourceManager.GetString("receipt_template", resourceCulture);
            }
        }
    }
}
