name: GitHub Releases

on:
  workflow_dispatch:

jobs:
  deploy-to-github-releases:
    
    runs-on: windows-latest

    env:
      Project_File_Path: XMLToPDFApp\XMLToPDFApp.csproj
      Project_File_Tag: AssemblyVersion
      Dotnet_Install_Version: "8.0.x"
      Repository_Url: https://github.com/ChrisK106/sunat-xml-to-pdf
      App_Id: SunatXmlToPdfApp
      Main_Executable: XMLToPDFApp.exe
      Required_Dependencies: net8-x64-desktop
      Splash_Image_Path: XMLToPDFApp\Resources\xml_filetype_icon_512.png
      Icon_Path: XMLToPDFApp\Resources\xml_filetype_icon_128.ico
      Pack_Title: SUNAT XML a PDF
      Pack_Authors: Christian Cano
      Sign_Params: "/td sha256 /fd sha256 /f Signing/GitHubActionsWorkflow.pfx /tr http://timestamp.sectigo.com /p ${{ secrets.Pfx_Key }}"
      
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Get Version from Project File
      id: get-version
      shell: bash
      run: echo "version=$(grep -oE '<$env:Project_File_Tag>[^<]+' $env:Project_File_Path | sed 's/<$env:Project_File_Tag>//')" >> $GITHUB_OUTPUT

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: $env:Dotnet_Install_Version
        
    - name: Publish Application
      run: dotnet publish $env:Project_File_Path -c Release -o publish -r win-x64 --self-contained false

    # Decode the base 64 encoded pfx and save the Signing Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path Signing -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Create Velopack Release and upload to Github Releases
      run: |
        dotnet tool install -g vpk
        vpk download github --repoUrl $env:Repository_Url
        vpk pack -u $env:App_Id -v ${{ steps.get-version.outputs.version }} -p publish -e $env:Main_Executable -f $env:Required_Dependencies -s $env:Splash_Image_Path -i $env:Icon_Path --packTitle $env:Pack_Title --packAuthors $env:Pack_Authors --signParams $env:Sign_Params
        vpk upload github --repoUrl $env:Repository_Url --publish --releaseName ${{ steps.get-version.outputs.version }} --tag ${{ steps.get-version.outputs.version }} --token ${{ secrets.GH_TOKEN }}
        
    - name: Remove the pfx
      run: Remove-Item -path Signing\GitHubActionsWorkflow.pfx
